### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by agrif** [msierks/mpq-rust#10]
Hello! Can you do a new release that incorporates the changes in commit 9812f69e8f1e4fb94523783e4fdbc0819733d3a7?

The 0.8.0 release works fine for me on Windows, but with exactly the same files on MacOS it treats my `common.MPQ` file as empty. It even claims the (listfile) is empty. However, the master branch of this repository works fine, and 9812f69e8f1e4fb94523783e4fdbc0819733d3a7 is the only substantive change since 0.8.0.

**Comment by msierks** [comment]
Done
